### ISSUE TITLE
`I0` or `IZ` to support -0 / --null / --zero based commands

### ISSUE THREAD

**Issue by Summertime** [zqqqqz2000/shshsh#3]
Example:
```python
for filename in IZ >> "ls --zero" | "grep --null-data test":
    print(filename)
```

---

`ls --zero`, `grep --null-data`, `xargs --null`, `find -print0`, `cut -zero-terminated`, etc all support such zero-suffixed data

**Comment by zqqqqz2000** [comment]
Now, you can use _IZ >> "ls --zero"_ for zero-suffixed data. you can reference the [test case](https://github.com/zqqqqz2000/shshsh/blob/main/tests/test_zero.py#L12).
Also, the detail usage will be updated in the readme later.
